/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Escalation = IDL.Record({
  'customerName' : IDL.Text,
  'escalationManager' : IDL.Text,
  'escalationTrend' : IDL.Text,
  'title' : IDL.Text,
  'referenceNumber' : IDL.Text,
  'projectName' : IDL.Text,
  'escalationStatus' : IDL.Text,
  'createdDate' : IDL.Text,
  'escalationType' : IDL.Text,
  'businessGroup' : IDL.Text,
  'mainContact' : IDL.Text,
  'currentStatus' : IDL.Text,
  'lengthOfEscalation' : IDL.Text,
  'product' : IDL.Text,
  'escalationNumber' : IDL.Text,
  'reason' : IDL.Text,
  'functionalArea' : IDL.Text,
  'deEscalationCriteria' : IDL.Text,
});
export const EscalationId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEscalation' : IDL.Func([Escalation], [EscalationId], []),
  'deleteEscalation' : IDL.Func([EscalationId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEscalation' : IDL.Func([EscalationId], [Escalation], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEscalations' : IDL.Func([], [IDL.Vec(Escalation)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEscalation' : IDL.Func([EscalationId, Escalation], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Escalation = IDL.Record({
    'customerName' : IDL.Text,
    'escalationManager' : IDL.Text,
    'escalationTrend' : IDL.Text,
    'title' : IDL.Text,
    'referenceNumber' : IDL.Text,
    'projectName' : IDL.Text,
    'escalationStatus' : IDL.Text,
    'createdDate' : IDL.Text,
    'escalationType' : IDL.Text,
    'businessGroup' : IDL.Text,
    'mainContact' : IDL.Text,
    'currentStatus' : IDL.Text,
    'lengthOfEscalation' : IDL.Text,
    'product' : IDL.Text,
    'escalationNumber' : IDL.Text,
    'reason' : IDL.Text,
    'functionalArea' : IDL.Text,
    'deEscalationCriteria' : IDL.Text,
  });
  const EscalationId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEscalation' : IDL.Func([Escalation], [EscalationId], []),
    'deleteEscalation' : IDL.Func([EscalationId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEscalation' : IDL.Func([EscalationId], [Escalation], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEscalations' : IDL.Func([], [IDL.Vec(Escalation)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEscalation' : IDL.Func([EscalationId, Escalation], [], []),
  });
};

export const init = ({ IDL }) => { return []; };