/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Escalation {
  'customerName' : string,
  'escalationManager' : string,
  'escalationTrend' : string,
  'title' : string,
  'referenceNumber' : string,
  'projectName' : string,
  'escalationStatus' : string,
  'createdDate' : string,
  'escalationType' : string,
  'businessGroup' : string,
  'mainContact' : string,
  'currentStatus' : string,
  'lengthOfEscalation' : string,
  'product' : string,
  'escalationNumber' : string,
  'reason' : string,
  'functionalArea' : string,
  'deEscalationCriteria' : string,
}
export type EscalationId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEscalation' : ActorMethod<[Escalation], EscalationId>,
  'deleteEscalation' : ActorMethod<[EscalationId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEscalation' : ActorMethod<[EscalationId], Escalation>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEscalations' : ActorMethod<[], Array<Escalation>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEscalation' : ActorMethod<[EscalationId, Escalation], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];