/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type EscalationId = bigint;
export interface Escalation {
    customerName: string;
    escalationManager: string;
    escalationTrend: string;
    title: string;
    escalationId: EscalationId;
    referenceNumber: string;
    projectName: string;
    escalationStatus: EscalationStatus;
    createdDate: bigint;
    escalationType: string;
    businessGroup: string;
    mainContact: string;
    currentStatus: string;
    product: string;
    escalationNumber: string;
    reason: string;
    functionalArea: string;
    deEscalationCriteria: string;
}
export interface EscalationResponse {
    customerName: string;
    escalationManager: string;
    escalationTrend: string;
    title: string;
    escalationId: EscalationId;
    referenceNumber: string;
    projectName: string;
    escalationStatus: EscalationStatus;
    createdDate: bigint;
    escalationType: string;
    businessGroup: string;
    mainContact: string;
    currentStatus: string;
    lengthOfEscalation: bigint;
    product: string;
    escalationNumber: string;
    reason: string;
    functionalArea: string;
    deEscalationCriteria: string;
}
export interface UserProfile {
    name: string;
}
export enum EscalationStatus {
    Red = "Red",
    Yellow = "Yellow",
    Assessment = "Assessment",
    Green = "Green",
    Resolved = "Resolved"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEscalation(title: string, reason: string, deEscalationCriteria: string, currentStatus: string, escalationManager: string, functionalArea: string, escalationTrend: string, escalationStatus: EscalationStatus, escalationType: string, mainContact: string, customerName: string, projectName: string, referenceNumber: string, businessGroup: string, product: string): Promise<EscalationId>;
    deleteEscalation(escalationId: EscalationId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEscalation(escalationId: EscalationId): Promise<EscalationResponse>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listEscalations(): Promise<Array<EscalationResponse>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateEscalation(escalationId: EscalationId, updatedEscalation: Escalation): Promise<void>;
}
import type { Escalation as _Escalation, EscalationId as _EscalationId, EscalationResponse as _EscalationResponse, EscalationStatus as _EscalationStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEscalation(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: EscalationStatus, arg8: string, arg9: string, arg10: string, arg11: string, arg12: string, arg13: string, arg14: string): Promise<EscalationId> {
        if (this.processError) {
            try {
                const result = await this.actor.createEscalation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_EscalationStatus_n3(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11, arg12, arg13, arg14);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEscalation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_EscalationStatus_n3(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11, arg12, arg13, arg14);
            return result;
        }
    }
    async deleteEscalation(arg0: EscalationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEscalation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEscalation(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEscalation(arg0: EscalationId): Promise<EscalationResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getEscalation(arg0);
                return from_candid_EscalationResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEscalation(arg0);
            return from_candid_EscalationResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listEscalations(): Promise<Array<EscalationResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEscalations();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEscalations();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateEscalation(arg0: EscalationId, arg1: Escalation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEscalation(arg0, to_candid_Escalation_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEscalation(arg0, to_candid_Escalation_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EscalationResponse_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EscalationResponse): EscalationResponse {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_EscalationStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EscalationStatus): EscalationStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    escalationManager: string;
    escalationTrend: string;
    title: string;
    escalationId: _EscalationId;
    referenceNumber: string;
    projectName: string;
    escalationStatus: _EscalationStatus;
    createdDate: bigint;
    escalationType: string;
    businessGroup: string;
    mainContact: string;
    currentStatus: string;
    lengthOfEscalation: bigint;
    product: string;
    escalationNumber: string;
    reason: string;
    functionalArea: string;
    deEscalationCriteria: string;
}): {
    customerName: string;
    escalationManager: string;
    escalationTrend: string;
    title: string;
    escalationId: EscalationId;
    referenceNumber: string;
    projectName: string;
    escalationStatus: EscalationStatus;
    createdDate: bigint;
    escalationType: string;
    businessGroup: string;
    mainContact: string;
    currentStatus: string;
    lengthOfEscalation: bigint;
    product: string;
    escalationNumber: string;
    reason: string;
    functionalArea: string;
    deEscalationCriteria: string;
} {
    return {
        customerName: value.customerName,
        escalationManager: value.escalationManager,
        escalationTrend: value.escalationTrend,
        title: value.title,
        escalationId: value.escalationId,
        referenceNumber: value.referenceNumber,
        projectName: value.projectName,
        escalationStatus: from_candid_EscalationStatus_n10(_uploadFile, _downloadFile, value.escalationStatus),
        createdDate: value.createdDate,
        escalationType: value.escalationType,
        businessGroup: value.businessGroup,
        mainContact: value.mainContact,
        currentStatus: value.currentStatus,
        lengthOfEscalation: value.lengthOfEscalation,
        product: value.product,
        escalationNumber: value.escalationNumber,
        reason: value.reason,
        functionalArea: value.functionalArea,
        deEscalationCriteria: value.deEscalationCriteria
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Red: null;
} | {
    Yellow: null;
} | {
    Assessment: null;
} | {
    Green: null;
} | {
    Resolved: null;
}): EscalationStatus {
    return "Red" in value ? EscalationStatus.Red : "Yellow" in value ? EscalationStatus.Yellow : "Assessment" in value ? EscalationStatus.Assessment : "Green" in value ? EscalationStatus.Green : "Resolved" in value ? EscalationStatus.Resolved : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EscalationResponse>): Array<EscalationResponse> {
    return value.map((x)=>from_candid_EscalationResponse_n8(_uploadFile, _downloadFile, x));
}
function to_candid_EscalationStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EscalationStatus): _EscalationStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Escalation_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Escalation): _Escalation {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    escalationManager: string;
    escalationTrend: string;
    title: string;
    escalationId: EscalationId;
    referenceNumber: string;
    projectName: string;
    escalationStatus: EscalationStatus;
    createdDate: bigint;
    escalationType: string;
    businessGroup: string;
    mainContact: string;
    currentStatus: string;
    product: string;
    escalationNumber: string;
    reason: string;
    functionalArea: string;
    deEscalationCriteria: string;
}): {
    customerName: string;
    escalationManager: string;
    escalationTrend: string;
    title: string;
    escalationId: _EscalationId;
    referenceNumber: string;
    projectName: string;
    escalationStatus: _EscalationStatus;
    createdDate: bigint;
    escalationType: string;
    businessGroup: string;
    mainContact: string;
    currentStatus: string;
    product: string;
    escalationNumber: string;
    reason: string;
    functionalArea: string;
    deEscalationCriteria: string;
} {
    return {
        customerName: value.customerName,
        escalationManager: value.escalationManager,
        escalationTrend: value.escalationTrend,
        title: value.title,
        escalationId: value.escalationId,
        referenceNumber: value.referenceNumber,
        projectName: value.projectName,
        escalationStatus: to_candid_EscalationStatus_n3(_uploadFile, _downloadFile, value.escalationStatus),
        createdDate: value.createdDate,
        escalationType: value.escalationType,
        businessGroup: value.businessGroup,
        mainContact: value.mainContact,
        currentStatus: value.currentStatus,
        product: value.product,
        escalationNumber: value.escalationNumber,
        reason: value.reason,
        functionalArea: value.functionalArea,
        deEscalationCriteria: value.deEscalationCriteria
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EscalationStatus): {
    Red: null;
} | {
    Yellow: null;
} | {
    Assessment: null;
} | {
    Green: null;
} | {
    Resolved: null;
} {
    return value == EscalationStatus.Red ? {
        Red: null
    } : value == EscalationStatus.Yellow ? {
        Yellow: null
    } : value == EscalationStatus.Assessment ? {
        Assessment: null
    } : value == EscalationStatus.Green ? {
        Green: null
    } : value == EscalationStatus.Resolved ? {
        Resolved: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
